site_name: Vadideki Geyik ğŸ¦Œ
copyright: Copyright Â©ï¸ Team Geyik â€” bu site kurabiye, Ã§erez, biskÃ¼vi, ve benzeri
  seni takip etmemizi saÄŸlayan teknolojileri katiyen kullanmaz. Bu siteyi ziyaret
  ettiÄŸinden haberimiz olmaz. Kim olduÄŸunu, nereden geldiÄŸini, neye tÄ±kladÄ±ÄŸÄ±nÄ±
  bilmiyoruz; rahat olâ€¦ popÃ¼ler davran, geyik kal ğŸ¦Œ.
theme:
  name: terminal
  custom_dir: overrides
  features:
    - navigation.top.hide

nav:
  - 'Ana Geyik ğŸ¦Œ': 'index.md'
  - 'Hemen Abone Ol ğŸ§': 'subscribe.md'
  - 'Biz Kimiz ğŸŒ³': 'team.md'
  - 'Merch ğŸ’': 'merch.md'
  - 'Bol Mazemos ğŸ±': 'bol-mazemos.md'
  - 'Geyik Akademi ğŸ“':
    - 'Ana Sayfa ğŸ«': 'geyik-akademi.md'
    - 'K8S101': 'k8s101/lecture001/000-prerequisites.md'
